{{ include "base.pvc" (list . "amplication-server.pvc") -}}
{{- define "amplication-server.pvc" -}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest }}
{{- end }}