{{ include "base.pvc" (list . "amplication-git-pull-service.pvc") -}}
{{- define "amplication-git-pull-service.pvc" -}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest }}
  storageClassName: aws-efs
{{- end }}