config:
  env:
    KAFKA_BROKER_URL_VAR: "localhost:9092"
    BASE_BUILDS_FOLDER: "/Users/ofekgabay/Documents/"
    GENERATE_PULL_REQUEST_TOPIC: "git.pr.generate.message"    

deployment:
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  podAnnotations: {}
  resources: {}
  image:
    pullPolicy: Always
    repository: 
    tag: 
    imagePullSecrets: []

service:
  type: ClusterIP
  port: 
    target: 3000
  protocol: TCP

ingress:
  enabled: false
