config:
  env:
    KAFKA_BROKER_IP_ENV_KEY: localhost:9092,localhost:9090
    WEBHOOKS_SECRET_KEY: [your webhooks secret key]
    KAFKA_REPOSITORY_PUSH_QUEUE: repositoryPush_created
    
deployment:
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  podAnnotations: {}
  resources: {}
  image:
    pullPolicy: Always
    repository: 
    tag: 
    imagePullSecrets: []

service:
  type: ClusterIP
  port: 
    target: 3000
  protocol: TCP

ingress:
  enabled: false
