config:
  env:
    ## for db connection
    POSTGRESQL_USER: admin
    POSTGRESQL_PASSWORD: admin
    POSTGRESQL_PORT: "5432"
    POSTGRESQL_URL: postgres://admin:admin@localhost:5432
    COMPOSE_PROJECT_NAME: amplication-git-pull-service

    ## kafka connection
    KAFKA_BROKERS: ["localhost:9092"]
    KAFKA_CONSUMER_GROUP: git-pull-event
    KAFKA_CLIENT_ID: repository-pull
    KAFKA_TOPIC: "pull.event"

    ## configurations
    NODE_ENV: developement
    STORAGE_PATH: /pull-data
    MAX_SNAPSHOTS:
    GIT_DEFAULT_ORIGIN_NAME: origin

    ## github integration
    GITHUB_APP_APP_ID:
    GITHUB_APP_PRIVATE_KEY:

deployment:
  replicaCount: 1
  volume:
  name: amplication-git-pull-data
  path: /pull-data
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  podAnnotations: {}
  resources: {}
  image:
    pullPolicy: Always
    repository: 
    tag: 
    imagePullSecrets: []

service:
  type: ClusterIP
  port: 
    target: 3000
  protocol: TCP

ingress:
  enabled: false

pvc:
  storageRequest: 1Gi
